In [4]:
# 1.1 Configuración del Entorno
import tensorflow as tf
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# Instalar librerías adicionales
!pip install seaborn plotly

# Importaciones estándar
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import warnings

warnings.filterwarnings('ignore')

# Configuración de visualización
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12

print("✅ Entorno configurado correctamente en Google Colab")

GPU disponible: []
✅ Entorno configurado correctamente en Google Colab


Notebook 1: Fundamentos de NumPy y Pandas

En este notebook exploraremos las bases de la manipulación de datos numéricos con **NumPy** y el análisis de dataframes con **Pandas**.

## Objetivos:
1. Crear y manipular arrays.
2. Cargar datasets (Titanic/Iris).
3. Realizar análisis exploratorio básico.

In [5]:
# --- PARTE 1: NUMPY ---

# Crear un array de datos aleatorios (simulando calificaciones de 0 a 10)
# Creamos una matriz de 5 estudiantes x 4 materias
calificaciones = np.random.randint(0, 11, size=(5, 4))

print("Matriz de Calificaciones (Filas=Estudiantes, Col=Materias):")
print(calificaciones)

# Calcular el promedio por estudiante (axis=1 recorre filas)
promedios_estudiantes = np.mean(calificaciones, axis=1)
print("\nPromedio por estudiante:", promedios_estudiantes)

# Filtrar estudiantes aprobados (Nota > 6)
aprobados = promedios_estudiantes > 6
print("\n¿Aprobó cada estudiante?:", aprobados)
print(f"Total de aprobados: {np.sum(aprobados)}")

Matriz de Calificaciones (Filas=Estudiantes, Col=Materias):
[[0 3 9 8]
 [3 9 3 2]
 [2 6 3 0]
 [5 3 2 3]
 [0 4 2 4]]

Promedio por estudiante: [5.   4.25 2.75 3.25 2.5 ]

¿Aprobó cada estudiante?: [False False False False False]
Total de aprobados: 0


In [6]:
# --- PARTE 2: PANDAS ---

# Cargar dataset Titanic desde Seaborn
df_titanic = sns.load_dataset('titanic')

# 1. Exploración inicial
print("Primeras 5 filas del dataset Titanic:")
display(df_titanic.head())

print("\nInformación del dataset:")
print(df_titanic.info())

# 2. Análisis Estadístico Básico
print("\nEstadísticas descriptivas (Edad y Tarifa):")
display(df_titanic[['age', 'fare']].describe())

# 3. Agrupación (Grouping)
# ¿Cuál fue la tasa de supervivencia por clase?
sobrevivientes_clase = df_titanic.groupby('class')['survived'].mean()
print("\nTasa de supervivencia por clase:")
print(sobrevivientes_clase)

Primeras 5 filas del dataset Titanic:


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True


Información del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None

Estadísticas descriptivas (Edad y Tarifa):


age        fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200


Tasa de supervivencia por clase:
class
First     0.629630
Second    0.472826
Third     0.242363
Name: survived, dtype: float64


In [15]:
import os

# --- 1. CONFIGURACIÓN EXACTA SEGÚN TU IMAGEN ---
# Datos de autenticación
user_git = "pcastroh-lgtm"                      # Tu usuario real (visto en la imagen)
repo_name = "UEES-IA-Semana1-CASTROPABLO"       # Tu repositorio
token = "TOKEN_ELIMINADO_POR_SEGURIDAD" # El token que generaste

# Datos para el historial de cambios (puedes dejarlos así o poner tu email real)
email_estudiante = "pablo.castro@estudiantes.uees.edu.ec"
nombre_estudiante = "Pablo Castro"

# --- 2. CONFIGURAR GIT ---
!git config --global user.email "{email_estudiante}"
!git config --global user.name "{nombre_estudiante}"

# --- 3. CLONAR EL REPOSITORIO (Usando el token para dar permiso) ---
# Si la carpeta ya existe, la borramos para evitar conflictos y clonamos de cero
if os.path.exists(repo_name):
    !rm -rf {repo_name}

print(f"🔄 Clonando {repo_name} desde la cuenta de {user_git}...")
!git clone https://{token}@github.com/{user_git}/{repo_name}.git

# Entramos a la carpeta
%cd {repo_name}

# --- 4. GUARDAR Y SUBIR EL NOTEBOOK ---
# Creamos la carpeta de destino obligatoria
!mkdir -p 02_Laboratorio/notebooks/

# Nombre exacto del archivo en Colab
notebook_filename = "01_Fundamentos_NumPy_Pandas.ipynb"

# Verificamos si el archivo existe en Colab y lo copiamos
if os.path.exists(f"/content/{notebook_filename}"):
    print(f"📄 Copiando {notebook_filename}...")
    !cp /content/{notebook_filename} ./02_Laboratorio/notebooks/

    # Comandos para subir a GitHub
    !git add .
    !git commit -m "Actualización automática: Notebook 1 terminado"
    !git push origin main

    print("\n✅ ¡ÉXITO! Tu archivo se ha subido correctamente.")
    print(f"Revisa tu GitHub aquí: https://github.com/{user_git}/{repo_name}")
else:
    print(f"\n❌ ERROR: No encuentro el archivo llamado '{notebook_filename}' en Colab.")
    print("👀 MIRA ARRIBA A LA IZQUIERDA: Asegúrate que el nombre de tu notebook sea EXACTAMENTE:")
    print(f"   {notebook_filename}")

🔄 Clonando UEES-IA-Semana1-CASTROPABLO desde la cuenta de pcastroh-lgtm...
Cloning into 'UEES-IA-Semana1-CASTROPABLO'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
Receiving objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
/content/UEES-IA-Semana1-CASTROPABLO/UEES-IA-Semana1-CASTROPABLO/UEES-IA-Semana1-CASTROPABLO

❌ ERROR: No encuentro el archivo llamado '01_Fundamentos_NumPy_Pandas.ipynb' en Colab.
👀 MIRA ARRIBA A LA IZQUIERDA: Asegúrate que el nombre de tu notebook sea EXACTAMENTE:
   01_Fundamentos_NumPy_Pandas.ipynb
